### ISSUE TITLE
Clarification of message passing algorithm

### ISSUE THREAD

**Issue by laurapspector** [gui11aume/starcode#32] opened 2019-08-12 16:11 UTC
Hi Eduard,

Can you please clarify the output for the message passing algorithm? In particular, in the situation in which a sequence could be clustered with more than one canonical sequence (due to settings for -r and -d), I understand that the sequence _counts_ are split between the two canonical sequences, but if I choose to print the resulting clusters using `--print-clusters`, will the sequence appear in the clusters for _both_ canonical sequences, or will it not appear at all? In my case, I prefer that it doesn't appear at all because I would like to throw out sequences that cluster ambiguously!

Thanks!

**Comment by ezorita** [comment] 2019-08-18 09:59
Hi laurapspector,

since the last version this behavior was modified. In particular, when there is an ambiguous clustering in MP (a sequence that is equally distant to two or more sequences), all its counts are passed to **only one** parent sequence. The parent that receives the counts is selected with the following criteria:

1. The canonical parent with more counts,
or in case of tie
2. The canonical parent whose match diversity is bigger (matches more different sequences)
or in case of tie
3. The parent whose parent has more counts (the number of counts of the grandparent)

if neither of these resolve the conflict it is assigned to one of them at random, but you can expect reproducibility in the choice.

I hope this clarifies your doubts.

Eduard

**Closed** 2019-09-03 09:29 UTC
