### ISSUE TITLE
Large dataset | memory error

### ISSUE THREAD

**Issue by vineeth-s** [gui11aume/starcode#41] opened 2021-11-05 14:28 UTC
I am trying to run starcode on a FASTQ that has ~ 3 Mio reads each 450 bp long with 40 threads on a machine that has 128GB RAM; at some point starcode has consumed all the memory and just exits quietly -- is this intended behaviour ?, it would perhaps be nice for it to exit gracefully saying data could not be processed ?

**Comment by gui11aume** [comment] 2021-11-05 14:43
Hi @vineeth-s! Thanks for notifying! I really appreciate that you take the time to do this. Of course, the intended behavior is to keep the user informed. In principle, the error should be

`error ERROR_TYPE in FUNCTION_NAME (FILENAME:LINE_NUMBER)`
`starcode has crashed, please contact guillaume.filion@gmail.com for support with this issue`

Perhaps I forgot to check the result of a memory allocation somewhere. Give me a few days to check if I can find the spot where this may happen in your case.

**Comment by vineeth-s** [comment] 2021-11-05 15:05
Also I am guessing there is no easy workaround for dealing with large datasets because iirc almost all of the heavylifting is done in memory ?

**Comment by vineeth-s** [comment] 2021-11-05 15:22
I am thinking a lazy workaround would be to split the FASTQ and take a map-reduce approach

**Comment by gui11aume** [comment] 2021-11-05 19:35
Early on, we designed the data structure in such a way that long sequences have a disproportionate footprint on memory. This was back in 2012 and most runs did not even have 50 nucleotides. Nowadays we would implement the trie in a different way, but that requires re-writing the core algorithm, which would bring so many new bugs. We no longer work on Starcode, so we prefer fix the bug of this version than develop a new one.

If there is some way you can make the input sequences shorter, you should see a substantial improvement. Reducing the maximum distance if you can should lower the memory footprint as well. Also, we have noticed some strange behavior in some Docker containers where the memory available to Starcode is reduced. If that applies to you, you could try running it on the host machine instead of the container. Finally, I don't have the numbers in mind, but based on the specifications you give, I am thinking that having 256 GB of RAM may do the trick.

If none of that works, then the problem is just too big for Starcode and you would have to chop it into smaller pieces.

**Comment by gui11aume** [comment] 2021-11-05 20:09
@vineeth-s I have created a new branch [bug/memory_errors](https://github.com/gui11aume/starcode/tree/bug/memory_errors). There were a few lines where error would not be properly reported. Would you pull this branch, compile starcode again and test it on your problem? With a bit of luck it will crash with a more information message this time.

**Comment by darachm** [comment] 2021-11-05 20:15
@vineeth-s If you are interested in trimming the sequences before feeding them into starcode, I have two tools that could help. One is a fuzzy regular-expression barcode parser [itermae](https://gitlab.com/darachm/itermae/), the other is a script to extract sequence to the left or right of an alignment in a SAM file [SAMlami slicer](https://gitlab.com/darachm/bps-dev/-/blob/master/scripts/samlami-slicer.py). But if this is rDNA or some other long marker, then I suppose that would not work!

**Comment by vineeth-s** [comment] 2021-11-08 16:55
> @vineeth-s I have created a new branch [bug/memory_errors](https://github.com/gui11aume/starcode/tree/bug/memory_errors). There were a few lines where error would not be properly reported. Would you pull this branch, compile starcode again and test it on your problem? With a bit of luck it will crash with a more information message this time.

I will try this at the earliest, thanks much

**Comment by vineeth-s** [comment] 2021-11-08 17:00
> @vineeth-s If you are interested in trimming the sequences before feeding them into starcode, I have two tools that could help. One is a fuzzy regular-expression barcode parser [itermae](https://gitlab.com/darachm/itermae/), the other is a script to extract sequence to the left or right of an alignment in a SAM file [SAMlami slicer](https://gitlab.com/darachm/bps-dev/-/blob/master/scripts/samlami-slicer.py). But if this is rDNA or some other long marker, then I suppose that would not work!

itermae will not be of help in my current problem but it definitely saves me a lot of time as I was beginning to write something similar for a related project -- this is exactly what I needed, much appreciated and obliged.

**Comment by gui11aume** [comment] 2021-11-15 06:50
@vineeth-s Let me know whether the problems are solved on the branch with the fix.

**Comment by MayLiu27** [comment] 2024-04-11 15:32
Having the same memory issue here. Starcode failed on a fastq with 35GB. Will it be possible to take gzipped file .fq.gz as input where it's only 3GB

**Comment by gui11aume** [comment] 2024-04-11 15:37
Hi @MayLiu27! What is the issue: that starcode crashes with a memory error, that it crashes without an error message, or that it crashes way before the memory of your computer runs out?

In any event, compressing the input file with gzip will probably not solve the issue.

**Comment by MayLiu27** [comment] 2024-04-18 15:26
> Hi @MayLiu27! What is the issue: that starcode crashes with a memory error, that it crashes without an error message, or that it crashes way before the memory of your computer runs out?
> 
> In any event, compressing the input file with gzip will probably not solve the issue.

I first got the error saying starcode is running with thread 1 (no other specific message shown), so I changed to -t 6, which then got the memory issue
```
Command error:
  tee: .command.log: No space left on device
  gzip: tee: .command.err: No space left on device
  stdout: No space left on device
```

I ran starcode in a Nextflow workflow. I had to increase the computes to have at least 300GB of disk space and to be scaled up to 700GB of RAM to have a successful run.

**Comment by gui11aume** [comment] 2024-04-18 15:52
I am glad that you got it to work! I will close the issue now.

**Closed** 2024-04-18 15:52 UTC
Labels: bug
